Add Haroon OOP Activity Folder
saadali18/OOP-interview-questions pull request #15
Opened 2024-01-24 13:53 UTC by HaroonShahid1

2024-01-24 18:08 UTC, saadali18 requested changes
Good and clean work.
Minor adjustments required. 
Remove .pdf files and rename your .cs file like question_1.cs something like previous fellows has done.

2024-01-24 18:08 UTC, saadali18 commented on Haroon Shahid-Batch03 OOP Activity/Hard/HardQuestion1.cs
> +using System;
Explain the concept theoretically in two or three statements first before directly jumping to code. 
For example: Abstraction
What explain what is abstraction then give code example

2024-01-24 18:35 UTC, HaroonShahid1 commented
Okay I understand, thanks you so much.

On Wed, Jan 24, 2024, 11:09 PM Saad Ali ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Good and clean work.
> Minor adjustments required.
> Remove .pdf files and rename your .cs file like question_1.cs something
> like previous fellows has done.
> ------------------------------
>
> In Haroon Shahid-Batch03 OOP Activity/Hard/HardQuestion1.cs
> <https://github.com/saadali18/OOP-interview-questions/pull/15#discussion_r1465356820>
> :
>
> > @@ -0,0 +1,40 @@
> +using System;
>
> Explain the concept theoretically in two or three statements first before
> directly jumping to code.
> For example: Abstraction
> What explain what is abstraction then give code example
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/saadali18/OOP-interview-questions/pull/15#pullrequestreview-1842068797>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZ3OA56GTTNC3JGJR44XTZ3YQFE4FAVCNFSM6AAAAABCIZR4C6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQNBSGA3DQNZZG4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-01-25 17:24 UTC, saadali18 approved these changes

2024-01-25 17:24 UTC, merged